[build]
  publish = "public"
  command = ""

[build.environment]
  PHP_VERSION = "8.1"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
